# Generated by Django 3.1.2 on 2020-10-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveApp', '0002_auto_20201010_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivethru',
            name='pick_day',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
