# Generated by Django 3.1.2 on 2020-10-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
