# Generated by Django 3.1.2 on 2020-10-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storeName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
