# Generated by Django 3.1.2 on 2020-10-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='activae',
            new_name='active',
        ),
    ]
