# Generated by Django 3.1.2 on 2020-10-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
