# Generated by Django 3.1.2 on 2020-10-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
